---
title: "FinalProject"
author: "Group-5"
date: "2024-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We need to install the following libraries

```{r}
library(dplyr)
library(ggplot2)
library(jsonlite)
library(ggthemes)
```

The data that we need for this project

```{r}
transactions_data
mcc_df <- mcc #after using jsonlite library to read it
users_data
```

Selecting the Files that we need so that our devices won't crash

```{r}
transactions_data1 <- transactions_data %>% select(date, client_id, amount, use_chip, merchant_id, merchant_city, mcc)

users_data1 <- users_data %>%  select(id, current_age, gender, yearly_income, credit_score, total_debt)
```

We need to clean all the data

```{r}
#Clean Up Process For Transactions CSV File
transactions_data1$amount = gsub("[$,-]", "", transactions_data1$amount) #Removing the $ sign and minus sign from the "amount" column'

transactions_data1$amount = as.numeric(transactions_data1$amount) #Converting the column into numerics

transactions_data1 <- transactions_data1 %>% 
  mutate(use_chip = ifelse(use_chip == "Chip Transaction", "Online Transaction", use_chip)) #Changing the "Chip Transaction" to "Online Transaction" for data consistency

transactions_data1$use_chip = as.factor(transactions_data1$use_chip) #Converting the transaction type into factors

#Clean Up Process For User Data File
users_data1$yearly_income = gsub("[$,]", "", users_data1$yearly_income) #Removing the $ sign
users_data1$yearly_income = as.numeric(users_data1$yearly_income) #Converting into a numeric

users_data1$total_debt = gsub("[$,]", "", users_data1$total_debt) #Removing the $ sign
users_data1$total_debt = as.numeric(users_data1$total_debt) #Converting into a numeric

head(users_data1)

#Clean Up Process For Merchant Categories JSON File
mcc_df$mcc = as.integer(mcc_df$mcc) #Converting the mcc code into integers

str(mcc_df) #Rechecking to see changes were made correctly

#Verifying changes
head(transactions_data)
head(users_data1)
head(mcc_df)
```



Then we will join all those columns into one df

```{r}
data <- transactions_data1 %>% left_join(users_data1, by=c("client_id"="id")) %>% left_join(mcc_df, by="mcc")

data
```

Now, we start the data visualization

```{r}
#Summarizing the transactions by transaction type and converting into percentage
transaction_type = data %>%
  group_by(use_chip) %>%
  summarize(count = n ())%>%
  mutate(percentage = count / sum(count) * 100)

#Creating a Pie Chart to Visualize
ggplot(transaction_type, aes(x = "", y = percentage, fill = use_chip,)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") + #Converting the bar plot into pie chart
  labs(title = "Transactions by Type", x = "", y = "") +
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_stack(vjust = 0.5)) +
  theme_minimal() +
  theme(legend.position = "right")
```

```{r}
# Payment Method Based on Merchant City
payment_by_location <- data %>%
  group_by(use_chip, merchant_city) %>%
  summarise(count = n(), .groups = 'drop') %>%
  arrange(desc(count)) %>%
  group_by(use_chip) %>%
  slice_max(count, n = 5) %>%
  ungroup() %>% 
  arrange(desc(count))

ggplot(payment_by_location, aes(x = reorder(merchant_city, -count), y = count, fill = use_chip)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Top 5 Cities by Payment Method", x = "Merchant City", y = "Total Transactions", color = "Payment Methods") +
  theme_economist() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust=1)) +
  facet_wrap(~ use_chip, scales = "free_y", ncol = 1)
```

```{r}
#Summarizing the transactions count by merchant city and selecting the top 10 cities
top_cities = data %>%
  group_by(merchant_city) %>%
  summarize(transaction_count = n()) %>%
  arrange(desc(transaction_count)) %>%
  slice_head(n = 10)

#Creating a Bar plot to visualize
ggplot(top_cities, aes(x = reorder(merchant_city, transaction_count), y = transaction_count)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Top 10 Merchant Cities by Transaction Count", x = "Merchant City", y = "Transaction Count") +
  theme_economist()
```

```{r}
#Summarizing the total transaction amount by business type and selecting the top 5 business categories
spending_category = data %>%
  group_by(transaction_type) %>%
  summarize(total_amount = sum(amount, na.rm = TRUE)) %>%
  arrange(desc(total_amount))%>%
  slice_max(total_amount, n = 5) %>%
  mutate(percentage = total_amount / sum(total_amount) * 100) #Calculating the percentage of each business type

ggplot(spending_category, aes(x = "", y = total_amount, fill = transaction_type)) + 
  geom_bar(stat = "identity", width = 1, color = "white", size = 0.8) +  # White borders around each slice
  coord_polar("y") +  # Convert bar chart to pie chart
  labs(title = "Spending by MCC Code Category", x = "", y = "") +  # Title and remove axis labels
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_stack(vjust = 0.5),  # Position percentage labels in the center
            color = "white", size = 3, fontface = "bold") +  # White bold text for readability
  scale_fill_brewer(palette = "Paired") +  # Use the Paired color palette
  theme_minimal() +  # Remove gridlines and background
  theme(
    legend.position = "right",  # Position legend to the right
    plot.title = element_text(size = 20, face = "bold", color = "darkblue", hjust = 0.5),  # Fancy title
    plot.margin = margin(30, 30, 30, 30)  # Add padding around the plot
  )
```
```{r}
#The number of transactions for each type and payment method
top_transactions <- data %>%
  group_by(use_chip, transaction_type) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  group_by(use_chip) %>%
  slice_head(n = 5)

ggplot(top_transactions, aes(x = reorder(transaction_type, -count), y = count, fill = use_chip)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Top 5 Transaction Types by Payment Method", x = "Transaction Type", y = "Count", color = "Payment Method") +
  theme_economist() +
  theme(axis.text.x = element_text(size=7, angle = 70, hjust=1, vjust=1))
```

```{r}
income = data %>%
  mutate(
    # Creating income bins based on yearly_income
    income_bin = cut(yearly_income,
                     breaks = c(0, 30000, 70000, 150000, Inf),
                     labels = c("Low", "Middle", "Upper Middle", "High"), 
                     right = FALSE), # This ensures that the bins are inclusive of the left side

    # Creating credit score categories based on credit_score
    credit_score_range = case_when(
      credit_score < 600 ~ "Low",
      credit_score >= 600 & credit_score < 700 ~ "Medium",
      credit_score >= 700 ~ "High",
      TRUE ~ NA_character_ # This ensures that NA values are handled if any
    )
  )

avg_spending = data %>%
  group_by(income_bin) %>%
  summarize(average_spending = mean(amount, na.rm = TRUE))

print(avg_spending)

ggplot(avg_spending, aes(x = income_bin, y = average_spending, fill = income_bin)) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  labs(
    title = "Average Spending by Income Bracket",
    x = "Income Bracket",
    y = "Average Spending"
  ) +
  theme_economist() +
  scale_fill_brewer(palette = "Set3")

#Linear regression to assess the relationship between yearly income and spending
lm_model <- lm(amount ~ yearly_income, data = sampled_data)
summary(lm_model)

# Print the model's coefficients
print(coef(lm_model))

# Plotting the linear regression between yearly income and transaction amount
ggplot(sampled_data, aes(x = yearly_income, y = amount)) +
  geom_point(alpha = 0.4) +  # Scatter plot of the data points
  geom_smooth(method = "lm", color = "blue", se = FALSE) +  # Adding the regression line
  labs(
    title = "Relationship between Yearly Income and Spending",
    x = "Yearly Income",
    y = "Transaction Amount"
  ) +
  theme_economist()
```

```{r}
avg_spending_by_age = data %>%
  group_by(current_age) %>%
  summarize(average_spending = mean(amount, na.rm = TRUE))

ggplot(avg_spending_by_age, aes(x = current_age, y = average_spending))+
 geom_point(alpha = 0.4, color = "blue") + # Scatter points
  geom_smooth(method = "lm", color = "red") + # Regression line
  labs(
    title = "Relationship between Age and Spending Amount",
    x = "Current Age",
    y = "Transaction Amount"
  ) +
  theme_economist()

#Linear regression to assess the relationship between current age and spending amount
lm_age_spending = lm(amount ~ current_age, data = data)
summary(lm_age_spending)

# Plotting the linear regression between Current Age and Transaction Amount
ggplot(sampled_data, aes(x = current_age, y = amount)) +
  geom_point(alpha = 0.4) +  # Scatter plot of the data points
  geom_smooth(method = "lm", color = "blue", se = FALSE) +  # Adding the regression line
  labs(
    title = "Relationship between Current Age and Spending",
    x = "Current Age",
    y = "Transaction Amount"
  ) +
  theme_economist()
```

```{r}
avg_debt_by_age = data %>%
  group_by(current_age) %>%
  summarize(average_debt = mean(total_debt, na.rm = TRUE))

# Plotting the relationship
ggplot(avg_debt_by_age, aes(x = current_age, y = average_debt)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", color = "blue") +
  labs(
    title = "Relationship between Age and Average Debt",
    x = "Age",
    y = "Average Debt"
  ) +
  theme_economist()

#Linear regression to assess the relationship between current age and total debt
lm_age_debt <- lm(total_debt ~ current_age, data = data)
summary(lm_age_debt)

# Plotting the linear regression between Current Age and Total Debt
ggplot(sampled_data, aes(x = current_age, y = total_debt)) +
  geom_point(alpha = 0.4) +  # Scatter plot of the data points
  geom_smooth(method = "lm", color = "blue", se = FALSE) +  # Adding the regression line
  labs(
    title = "Relationship between Total Debt and Current Age",
    x = "Age",
    y = "Total Debt"
  ) +
  theme_economist()
```

```{r}
lm_multiple <- lm(amount ~ current_age + credit_score + yearly_income, data = data)
summary(lm_multiple)
```

```{r}
#TimeSeriesAnalysis on Payment Method Overtime
data$date <- as.Date(data$date)

time_series_data <- data %>%
  group_by(date, use_chip) %>%
  summarise(total_amount = sum(amount), .groups = 'drop')

ggplot(time_series_data, aes(x = date, y = total_amount, color = use_chip, group = use_chip)) +
  geom_line(size = 0.2) +
  labs(title = "Time Series Analysis of Payment Methods", x = "Date", y = "Total Amount", color = "Payment Methods") +
  theme_economist() +
  theme(axis.text.x = element_text(angle = 45, hjust=1, vjust=1))
```

